-- begin SAAS_ORDER
alter table SAAS_ORDER add constraint FK_SAAS_ORDER_CUSTOMER_ID foreign key (CUSTOMER_ID) references SAAS_CUSTOMER(ID)^
alter table SAAS_ORDER add constraint FK_SAAS_ORDER_PAYMENT_METHOD_ID foreign key (PAYMENT_METHOD_ID) references SAAS_PAYMENT_METHOD(ID)^
create index IDX_SAAS_ORDER_PAYMENT_METHOD on SAAS_ORDER (PAYMENT_METHOD_ID)^
create index IDX_SAAS_ORDER_CUSTOMER on SAAS_ORDER (CUSTOMER_ID)^
-- end SAAS_ORDER
